# Generated by Django 6.0.6 on 2026-08-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('collector', '吃谷人'), ('club', '社团')], db_index=True, default='collector', max_length=20, verbose_name='业务身份'),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', '审批中'), ('approved', '已审批')], db_index=True, default='approved', max_length=20, verbose_name='审批状态'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='社团名称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clubs/avatars/', verbose_name='社团头像')),
                ('description', models.TextField(blank=True, default='', verbose_name='社团简介')),
                ('announcement', models.TextField(blank=True, default='', verbose_name='社团公告')),
                ('contact_name', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='联系邮箱')),
                ('store_links', models.JSONField(blank=True, default=list, verbose_name='店铺链接')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='地址')),
                ('business_hours', models.CharField(blank=True, default='', max_length=200, verbose_name='营业时间')),
                ('application_reason', models.TextField(blank=True, default='', verbose_name='申请理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_profile', to='users.user', verbose_name='社团账号')),
            ],
            options={
                'verbose_name': '社团',
                'verbose_name_plural': '社团',
                'ordering': ['name', 'id'],
            },
        ),
    ]
