# Generated by Django 6.0.6 on 2026-09-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'created_at'], name='users_user_is_acti_6571b0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active', 'created_at'], name='users_user_role_id_9a329b_idx'),
        ),
    ]
