# Generated by Django 6.0.6 on 2026-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_users_user_is_acti_6571b0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='注销时间'),
        ),
    ]
