# Generated by Django 6.0.6 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_club_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.PositiveBigIntegerField(
                default=1,
                editable=False,
                verbose_name="Token版本",
            ),
        ),
    ]
