# Generated by Django 6.0.6 on 2026-08-13 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0034_goodscraft'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='预购ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='手办名称')),
                ('platform', models.CharField(blank=True, default='', help_text='例如：淘宝、天猫、京东、拼多多、代购等', max_length=50, verbose_name='下单平台')),
                ('shop_name', models.CharField(blank=True, default='', max_length=100, verbose_name='店铺名称')),
                ('order_no', models.CharField(blank=True, default='', max_length=100, verbose_name='订单号')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='定金金额')),
                ('balance_amount', models.DecimalField(blank=True, decimal_places=2, help_text='未知可留空', max_digits=10, null=True, verbose_name='尾款金额')),
                ('estimated_month', models.DateField(db_index=True, help_text='月份粒度，统一存当月 1 日', verbose_name='预计补款月份')),
                ('status', models.CharField(choices=[('pending', '待补款'), ('paid', '已补款'), ('cancelled', '已取消'), ('converted', '已转正')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='补款时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorder_source', to='goods.goods', verbose_name='转正后的谷子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='users.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '预购登记',
                'verbose_name_plural': '预购登记',
                'ordering': ['estimated_month', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='通知ID')),
                ('type', models.CharField(choices=[('preorder_soon', '即将补款'), ('preorder_due', '已到补款期'), ('preorder_cancelled', '已取消补款'), ('preorder_converted', '已转正')], max_length=30, verbose_name='通知类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('is_stale', models.BooleanField(db_index=True, default=False, help_text='预计月份修改或取消后置 True，界面置灰展示', verbose_name='是否已过期')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user', verbose_name='接收用户')),
                ('preorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reminder.preorder', verbose_name='关联预购')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'preorder', 'type', 'is_stale'), name='unique_active_user_preorder_notification_type')],
            },
        ),
    ]
