# Generated by Django 6.0.6 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_active_user_preorder_notification_type',
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_stale', False)), fields=('user', 'preorder', 'type'), name='unique_active_user_preorder_notification_type'),
        ),
    ]
