# Generated by Django 6.0.6 on 2026-08-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_remove_notification_unique_active_user_preorder_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='time_granularity',
            field=models.CharField(choices=[('month', '按月'), ('quarter', '按季度')], default='month', help_text='month=按具体月份补款；quarter=按季度补款（estimated_month 存季度首月）', max_length=10, verbose_name='时间粒度'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='estimated_month',
            field=models.DateField(db_index=True, help_text='时间粒度起点：按月存当月 1 日，按季度存季度首月 1 日', verbose_name='预计补款时间'),
        ),
    ]
