# Generated by Django 6.1 on 2026-08-17 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_preorder_time_granularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='delay_count',
            field=models.PositiveIntegerField(default=0, help_text='厂家跳票延期累计次数（跳票延期动作递增）', verbose_name='延期次数'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('preorder_soon', '即将补款'), ('preorder_due', '已到补款期'), ('preorder_cancelled', '已取消补款'), ('preorder_converted', '已转正'), ('preorder_delayed', '已延期')], max_length=30, verbose_name='通知类型'),
        ),
        migrations.CreateModel(
            name='PreorderDelayRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('from_month', models.DateField(help_text='粒度起点：按月存当月 1 日，按季度存季度首月 1 日', verbose_name='原预计补款时间')),
                ('to_month', models.DateField(help_text='粒度起点：按月存当月 1 日，按季度存季度首月 1 日', verbose_name='延期后补款时间')),
                ('from_granularity', models.CharField(choices=[('month', '按月'), ('quarter', '按季度')], max_length=10, verbose_name='原时间粒度')),
                ('to_granularity', models.CharField(choices=[('month', '按月'), ('quarter', '按季度')], max_length=10, verbose_name='延期后时间粒度')),
                ('reason', models.CharField(default='厂家跳票', max_length=100, verbose_name='延期原因')),
                ('note', models.TextField(blank=True, default='', help_text='选填，如官方公告延期到某月等', verbose_name='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_records', to='reminder.preorder', verbose_name='关联预购')),
            ],
            options={
                'verbose_name': '预购延期记录',
                'verbose_name_plural': '预购延期记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
