# Generated by Django 6.0.6 on 2026-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_preorder_delay_count_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='gamification_spend_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='成就消费变更时间'),
        ),
    ]
