# Generated by Django 6.0.6 on 2026-06-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_alter_goods_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shape_type',
            field=models.CharField(blank=True, help_text='用于图片自动分类：round（圆形吧唧类）/ rectangle（方形卡片类）', max_length=20, null=True, verbose_name='形状类型'),
        ),
    ]
