# Generated by Codex on 2026-06-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0024_category_shape_type"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="谷子名称")),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="入手日期"),
                ),
                ("is_official", models.BooleanField(default=False, verbose_name="是否官谷")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "characters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="theme_templates",
                        to="goods.character",
                        verbose_name="角色",
                    ),
                ),
                (
                    "ip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="theme_templates",
                        to="goods.ip",
                        verbose_name="IP作品",
                    ),
                ),
                (
                    "theme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template",
                        to="goods.theme",
                        verbose_name="关联主题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_templates",
                        to="users.user",
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "主题模板",
                "verbose_name_plural": "主题模板",
                "ordering": ["-updated_at"],
            },
        ),
    ]
