# Generated by Django 6.0.6 on 2026-06-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_ip_bgm_ids'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGMSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', '定时调度'), ('manual', '手动触发')], db_index=True, max_length=20, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('running', '执行中'), ('succeeded', '全部成功'), ('partial', '部分成功'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='running', max_length=20, verbose_name='任务状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_ips', models.IntegerField(default=0, verbose_name='处理 IP 总数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过数')),
                ('created_total', models.IntegerField(default=0, verbose_name='新增角色合计')),
                ('linked_total', models.IntegerField(default=0, verbose_name='回填 ID 合计')),
                ('error_message', models.TextField(blank=True, help_text='仅记录任务级别异常，单 IP 失败明细见 items', null=True, verbose_name='顶层错误摘要')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='手动触发时填，定时为 null', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgm_sync_jobs', to='users.user', verbose_name='触发人')),
            ],
            options={
                'verbose_name': 'BGM 同步任务',
                'verbose_name_plural': 'BGM 同步任务',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BGMSyncJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_name_snapshot', models.CharField(help_text='冗余保存，IP 被删除后仍可看名字', max_length=100, verbose_name='IP 名称快照')),
                ('bgm_subject_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='BGM 作品 ID 快照')),
                ('status', models.CharField(choices=[('success', '成功'), ('no_change', '无变更'), ('skipped_unbound', '未绑定，跳过'), ('error', '失败')], db_index=True, max_length=20, verbose_name='处理结果')),
                ('created_count', models.IntegerField(default=0, verbose_name='本次新增角色数')),
                ('linked_count', models.IntegerField(default=0, verbose_name='本次回填 ID 数')),
                ('subject_type_updated', models.BooleanField(default=False, verbose_name='是否更新 subject_type')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgm_sync_items', to='goods.ip', verbose_name='对应 IP')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='goods.bgmsyncjob', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': 'BGM 同步明细',
                'verbose_name_plural': 'BGM 同步明细',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BGMSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='生产环境默认关闭。开启后调度器会按 frequency 周期触发同步。', verbose_name='自动同步开关')),
                ('frequency', models.CharField(choices=[('daily', '每天'), ('every_3_days', '每3天'), ('weekly', '每周')], default='weekly', max_length=20, verbose_name='同步频率')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_at', models.DateTimeField(blank=True, help_text='由调度器根据 last_run_at + frequency 自动计算', null=True, verbose_name='下次执行时间')),
                ('concurrency_limit', models.IntegerField(default=1, help_text='预留字段；当前实现为串行同步', verbose_name='并发上限')),
                ('request_interval_ms', models.IntegerField(default=1500, help_text='礼貌地避免对 BGM API 过快请求', verbose_name='IP 间请求间隔(ms)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user', verbose_name='最近修改人')),
            ],
            options={
                'verbose_name': 'BGM 同步配置',
                'verbose_name_plural': 'BGM 同步配置',
            },
        ),
        migrations.AddIndex(
            model_name='bgmsyncjob',
            index=models.Index(fields=['trigger', 'started_at'], name='goods_bgmsy_trigger_2e522a_idx'),
        ),
        migrations.AddIndex(
            model_name='bgmsyncjob',
            index=models.Index(fields=['status', 'started_at'], name='goods_bgmsy_status_ebf158_idx'),
        ),
        migrations.AddIndex(
            model_name='bgmsyncjobitem',
            index=models.Index(fields=['job', 'status'], name='goods_bgmsy_job_id_02ecd6_idx'),
        ),
    ]
