# Generated by Django 6.0.6 on 2026-06-27 07:01

import apps.goods.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0028_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='手帐页版本ID')),
                ('version_no', models.PositiveIntegerField(db_index=True, verbose_name='版本号')),
                ('content', models.JSONField(default=apps.goods.models.default_journal_page_content, verbose_name='图层内容')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='journals/version_previews/', verbose_name='版本预览图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='goods.journalpage', verbose_name='所属手帐页')),
            ],
            options={
                'verbose_name': '手帐页版本',
                'verbose_name_plural': '手帐页版本',
                'ordering': ['-version_no'],
                'unique_together': {('page', 'version_no')},
            },
        ),
    ]
