# Generated by Django 6.0.6 on 2026-07-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0032_journalpage_share_token'),
        ('location', '0007_storagenode_workbench_fields'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['location'], name='goods_goods_locatio_33c2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['user', 'location'], name='goods_goods_user_id_7c5a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['created_at'], name='goods_goods_created_30fb46_idx'),
        ),
    ]
