# Generated by Django 6.0.6 on 2026-08-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0034_goodscraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shape_type',
            field=models.CharField(blank=True, choices=[('round', '圆形'), ('square', '正方形'), ('rectangle', '长方形')], help_text='用于图片自动分类：round（圆形）/ square（正方形）/ rectangle（长方形）', max_length=20, null=True, verbose_name='形状类型'),
        ),
    ]
