# Generated by Django 6.0.6 on 2026-08-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0035_alter_category_shape_type'),
        ('location', '0007_storagenode_workbench_fields'),
        ('users', '0002_user_account_type_user_approval_status_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='社团谷子可临时下架；个人谷子此字段无公开意义', verbose_name='是否公开发布'),
        ),
        migrations.AddField(
            model_name='goods',
            name='source_club_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_goods', to='goods.goods', verbose_name='来源社团谷子'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('intended', '意向入手'), ('in_cabinet', '在馆'), ('outdoor', '出街中'), ('sold', '已售出')], default='in_cabinet', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['source_club_goods', 'user'], name='goods_goods_source__6d266e_idx'),
        ),
        migrations.AddConstraint(
            model_name='goods',
            constraint=models.UniqueConstraint(condition=models.Q(('source_club_goods__isnull', False)), fields=('user', 'source_club_goods'), name='unique_user_source_club_goods'),
        ),
    ]
