# Generated by Django 6.0.6 on 2026-08-30 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _legacy_catalog_snapshot(goods):
    return {
        "legacy_goods_id": str(goods.id),
        "name": goods.name,
        "ip_id": goods.ip_id,
        "category_id": goods.category_id,
        "theme_id": goods.theme_id,
        "characters": list(goods.characters.values_list("id", flat=True)),
        "price": str(goods.price) if goods.price is not None else None,
        "purchase_date": goods.purchase_date.isoformat() if goods.purchase_date else None,
        "is_official": goods.is_official,
        "status": goods.status,
        "is_published": goods.is_published,
        "main_photo": goods.main_photo.name if goods.main_photo else None,
        "additional_photos": [
            {"name": photo.image.name, "label": photo.label}
            for photo in goods.additional_photos.all()
        ],
    }


def migrate_legacy_club_goods(apps, schema_editor):
    Goods = apps.get_model("goods", "Goods")
    GuziImage = apps.get_model("goods", "GuziImage")
    ClubCatalogItem = apps.get_model("goods", "ClubCatalogItem")
    ClubCatalogImage = apps.get_model("goods", "ClubCatalogImage")
    ClubGoodsOrigin = apps.get_model("goods", "ClubGoodsOrigin")
    ClubGoodsImportEvent = apps.get_model("goods", "ClubGoodsImportEvent")
    User = apps.get_model("users", "User")
    Club = apps.get_model("users", "Club")

    legacy_items = {}
    club_users = User.objects.filter(account_type="club")
    for goods in Goods.objects.filter(user__in=club_users).select_related("user", "ip", "category", "theme"):
        try:
            club = Club.objects.get(user_id=goods.user_id)
        except Club.DoesNotExist:
            continue
        publication_status = "draft" if goods.status == "draft" else ("unlisted" if not goods.is_published else "listed")
        item = ClubCatalogItem.objects.create(
            id=goods.id,
            club_id=club.id,
            name=goods.name,
            description=goods.notes or "",
            ip_id=goods.ip_id,
            category_id=goods.category_id,
            theme_id=goods.theme_id,
            main_photo=goods.main_photo.name if goods.main_photo else None,
            public_price=goods.price,
            is_official=goods.is_official,
            publication_status=publication_status,
            order=goods.order,
            created_at=goods.created_at,
            updated_at=goods.updated_at,
        )
        item.characters.set(goods.characters.values_list("id", flat=True))
        for photo in GuziImage.objects.filter(guzi_id=goods.id):
            ClubCatalogImage.objects.create(item_id=item.id, image=photo.image.name, label=photo.label)
        legacy_items[str(goods.id)] = item

    unlinked_personal_goods = 0
    personal_goods = Goods.objects.filter(source_club_goods__isnull=False).select_related("user", "source_club_goods")
    for goods in personal_goods:
        source_item = legacy_items.get(str(goods.source_club_goods_id))
        if source_item is None:
            unlinked_personal_goods += 1
        snapshot = _legacy_catalog_snapshot(goods.source_club_goods)
        origin = ClubGoodsOrigin.objects.create(
            collector_id=goods.user_id,
            source_item_id=source_item.id if source_item else None,
            personal_goods_id=goods.id,
            first_source_snapshot=snapshot,
        )
        ClubGoodsImportEvent.objects.create(
            origin_id=origin.id,
            operation="created",
            quantity_added=goods.quantity,
            source_snapshot=snapshot,
            goods_snapshot={
                "goods_id": str(goods.id),
                "name": goods.name,
                "quantity": goods.quantity,
                "price": str(goods.price) if goods.price is not None else None,
                "purchase_date": goods.purchase_date.isoformat() if goods.purchase_date else None,
                "status": goods.status,
                "notes": goods.notes or "",
            },
        )

    print(
        "Club catalog migration: "
        f"{unlinked_personal_goods} personal goods records could not be linked to a migrated source; "
        "they were retained as personal inventory."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0037_normalize_club_goods_quantity'),
        ('users', '0002_user_account_type_user_approval_status_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCatalogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club_catalog/extra/', verbose_name='图片')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片标签')),
            ],
            options={
                'verbose_name': '社团目录附加图片',
                'verbose_name_plural': '社团目录附加图片',
            },
        ),
        migrations.CreateModel(
            name='ClubCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='目录条目ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='谷子名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='公开说明')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='club_catalog/main/', verbose_name='主图')),
                ('public_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='公开价格')),
                ('is_official', models.BooleanField(default=True, verbose_name='是否官谷')),
                ('publication_status', models.CharField(choices=[('draft', '草稿'), ('listed', '上架'), ('unlisted', '下架')], db_index=True, default='draft', max_length=20, verbose_name='发布状态')),
                ('order', models.BigIntegerField(db_index=True, default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社团目录条目',
                'verbose_name_plural': '社团目录条目',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubGoodsImportEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='导入事件ID')),
                ('operation', models.CharField(choices=[('created', '首次导入'), ('merged', '合并数量')], max_length=20, verbose_name='操作')),
                ('quantity_added', models.PositiveIntegerField(default=1, verbose_name='增加数量')),
                ('source_snapshot', models.JSONField(default=dict, verbose_name='导入时来源快照')),
                ('goods_snapshot', models.JSONField(default=dict, verbose_name='导入后个人库存快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '社团谷子导入事件',
                'verbose_name_plural': '社团谷子导入事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubGoodsOrigin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='来源关系ID')),
                ('first_source_snapshot', models.JSONField(default=dict, verbose_name='首次来源快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次导入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最近导入时间')),
            ],
            options={
                'verbose_name': '社团谷子来源关系',
                'verbose_name_plural': '社团谷子来源关系',
            },
        ),
        migrations.RemoveConstraint(
            model_name='goods',
            name='unique_user_source_club_goods',
        ),
        migrations.RemoveIndex(
            model_name='goods',
            name='goods_goods_source__6d266e_idx',
        ),
        migrations.AddField(
            model_name='clubcatalogitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_catalog_items', to='goods.category', verbose_name='品类'),
        ),
        migrations.AddField(
            model_name='clubcatalogitem',
            name='characters',
            field=models.ManyToManyField(related_name='club_catalog_items', to='goods.character', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='clubcatalogitem',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='users.club', verbose_name='所属社团'),
        ),
        migrations.AddField(
            model_name='clubcatalogitem',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_catalog_items', to='goods.ip', verbose_name='IP作品'),
        ),
        migrations.AddField(
            model_name='clubcatalogitem',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_catalog_items', to='goods.theme', verbose_name='主题'),
        ),
        migrations.AddField(
            model_name='clubcatalogimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='goods.clubcatalogitem', verbose_name='目录条目'),
        ),
        migrations.AddField(
            model_name='clubgoodsorigin',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_goods_origins', to='users.user', verbose_name='吃谷人'),
        ),
        migrations.AddField(
            model_name='clubgoodsorigin',
            name='personal_goods',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_goods_origin', to='goods.goods', verbose_name='个人库存'),
        ),
        migrations.AddField(
            model_name='clubgoodsorigin',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_origins', to='goods.clubcatalogitem', verbose_name='来源社团条目'),
        ),
        migrations.AddField(
            model_name='clubgoodsimportevent',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='goods.clubgoodsorigin', verbose_name='来源关系'),
        ),
        migrations.RunPython(migrate_legacy_club_goods, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='goods',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='source_club_goods',
        ),
        migrations.AddIndex(
            model_name='clubcatalogitem',
            index=models.Index(fields=['club', 'publication_status'], name='goods_clubc_club_id_33732a_idx'),
        ),
        migrations.AddIndex(
            model_name='clubcatalogitem',
            index=models.Index(fields=['club', 'order', '-created_at'], name='goods_clubc_club_id_9a8d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='clubgoodsorigin',
            index=models.Index(fields=['collector', 'source_item'], name='goods_clubg_collect_7b41a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubgoodsorigin',
            constraint=models.UniqueConstraint(condition=models.Q(('collector__isnull', False), ('source_item__isnull', False)), fields=('collector', 'source_item'), name='unique_collector_club_catalog_origin'),
        ),
    ]
