# Generated by Django 6.0.6 on 2026-08-30

from django.db import migrations, models


def normalize_club_catalog_items(apps, schema_editor):
    ClubCatalogItem = apps.get_model("goods", "ClubCatalogItem")
    ClubCatalogItem.objects.all().update(is_official=False)


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0038_club_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubcatalogitem",
            name="is_official",
            field=models.BooleanField(default=False, verbose_name="是否官谷"),
        ),
        migrations.RunPython(normalize_club_catalog_items, migrations.RunPython.noop),
    ]
