# Generated by Django 6.0.6 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0039_club_catalog_is_fanmade"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubcatalogitem",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="定时上架时间",
            ),
        ),
        migrations.AddField(
            model_name="clubcatalogitem",
            name="publish_failed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="定时上架失败时间",
            ),
        ),
        migrations.AddField(
            model_name="clubcatalogitem",
            name="publish_error",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="定时上架失败原因",
            ),
        ),
    ]
