# Generated by Django 6.0.6 on 2026-09-13 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0040_club_catalog_publish_schedule"),
        ("users", "0004_clubfavorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsImageFingerprint",
            fields=[
                (
                    "goods",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="image_fingerprint",
                        serialize=False,
                        to="goods.goods",
                        verbose_name="谷子",
                    ),
                ),
                ("phash", models.CharField(db_index=True, max_length=16, verbose_name="感知哈希")),
                ("embedding", models.BinaryField(verbose_name="视觉向量")),
                (
                    "embedding_dim",
                    models.PositiveSmallIntegerField(default=384, verbose_name="向量维度"),
                ),
                (
                    "algorithm_version",
                    models.CharField(db_index=True, max_length=64, verbose_name="算法版本"),
                ),
                ("source_name", models.CharField(max_length=500, verbose_name="源主图路径")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "谷子主图指纹",
                "verbose_name_plural": "谷子主图指纹",
                "ordering": ["goods_id"],
                "indexes": [
                    models.Index(
                        fields=["algorithm_version", "goods"],
                        name="goods_goods_algorit_0a8cd8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GoodsImageMatchAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="识别记录ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("matched", "高置信匹配"),
                            ("candidates", "相似候选"),
                            ("not_found", "未找到"),
                        ],
                        max_length=20,
                        verbose_name="识别结论",
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(max_length=64, verbose_name="算法版本"),
                ),
                (
                    "top_score",
                    models.FloatField(blank=True, null=True, verbose_name="最高相似度"),
                ),
                (
                    "top_margin",
                    models.FloatField(blank=True, null=True, verbose_name="领先幅度"),
                ),
                (
                    "candidate_results",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="仅保存商品ID、分数和置信度，不保存查询图片。",
                        verbose_name="候选结果",
                    ),
                ),
                (
                    "feedback",
                    models.CharField(
                        choices=[
                            ("none", "未反馈"),
                            ("confirmed", "确认命中"),
                            ("rejected", "均不匹配"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=20,
                        verbose_name="用户反馈",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="创建时间",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "confirmed_goods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image_match_confirmations",
                        to="goods.goods",
                        verbose_name="确认命中的谷子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_image_match_attempts",
                        to="users.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "谷子图片识别记录",
                "verbose_name_plural": "谷子图片识别记录",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="goods_goods_user_id_8d52c5_idx",
                    ),
                    models.Index(
                        fields=["feedback", "-created_at"],
                        name="goods_goods_feedbac_9d7c62_idx",
                    ),
                ],
            },
        ),
    ]
