# Generated by Django 6.0.6 on 2026-09-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0041_goodsimagefingerprint_goodsimagematchattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='character',
            field=models.ForeignKey(blank=True, help_text='设置后可作为角色痛柜识别依据。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcases', to='goods.character', verbose_name='主角色'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='decoration_effect_code',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='痛柜效果编码'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='decoration_theme_code',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='痛柜主题编码'),
        ),
    ]
