# Generated by Django 6.0.6 on 2026-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0042_showcase_character_showcase_decoration_effect_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='gamification_valid_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='成就痛柜生效时间'),
        ),
    ]
