# Generated by Django 6.0.6 on 2026-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0043_showcase_gamification_valid_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='gamification_quantity_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='成就件数变更时间'),
        ),
        migrations.AddField(
            model_name='goods',
            name='gamification_spend_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='成就消费变更时间'),
        ),
    ]
