# Generated by Django 6.0.6 on 2026-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0044_goods_gamification_quantity_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='gamification_scope_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='成就维度变更时间'),
        ),
    ]
