# Generated by Django 6.0.6 on 2026-09-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0045_goods_gamification_scope_changed_at'),
        ('location', '0007_storagenode_workbench_fields'),
        ('users', '0006_user_users_user_is_acti_6571b0_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['ip', 'created_at'], name='goods_chara_ip_id_248385_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['bgm_character_id'], name='goods_chara_bgm_cha_0c2124_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['status', 'created_at'], name='goods_goods_status_5d0b82_idx'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['user', 'created_at'], name='goods_goods_user_id_e81b60_idx'),
        ),
        migrations.AddIndex(
            model_name='ip',
            index=models.Index(fields=['subject_type', 'order'], name='goods_ip_subject_daa29f_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['user', 'created_at'], name='goods_theme_user_id_c644e4_idx'),
        ),
    ]
