# Generated by Django 6.0.6 on 2026-09-19 06:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_origin_club(apps, schema_editor):
    ClubGoodsOrigin = apps.get_model("goods", "ClubGoodsOrigin")
    rows = ClubGoodsOrigin.objects.select_related("source_item").all()
    for origin in rows.iterator():
        club_id = origin.source_item.club_id if origin.source_item_id else None
        if club_id is None:
            snapshot = origin.first_source_snapshot or {}
            club_id = snapshot.get("club_id")
        if club_id is not None and origin.club_id != club_id:
            ClubGoodsOrigin.objects.filter(pk=origin.pk).update(club_id=club_id)


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0045_goods_gamification_scope_changed_at'),
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubgoodsorigin',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_origins', to='users.club', verbose_name='来源社团'),
        ),
        migrations.RunPython(backfill_origin_club, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='clubgoodsorigin',
            index=models.Index(fields=['club', 'collector'], name='goods_clubg_club_id_f98254_idx'),
        ),
    ]
