# Generated by Django 6.0.6 on 2026-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0048_merge_0046_goods_indexes_0047_club_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubgoodsimportevent',
            name='effective_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='首次进入有效状态时间'),
        ),
        migrations.AddField(
            model_name='goods',
            name='gamification_eligible_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='成就状态首次有效时间'),
        ),
    ]
