# Generated by Django 6.0.6 on 2026-09-19 10:00

import json
from hashlib import sha256

from django.db import migrations, models


ELIGIBLE_GOODS_STATUSES = {"in_cabinet", "outdoor", "sold"}


def backfill_gamification_lifecycle(apps, schema_editor):
    Goods = apps.get_model("goods", "Goods")
    ClubGoodsImportEvent = apps.get_model("goods", "ClubGoodsImportEvent")
    MetricSourceState = apps.get_model("gamification", "MetricSourceState")

    Goods.objects.filter(gamification_scope_changed_at__isnull=True).update(
        gamification_scope_changed_at=models.F("updated_at")
    )
    Goods.objects.filter(
        status__in=ELIGIBLE_GOODS_STATUSES,
        gamification_eligible_since__isnull=True,
    ).update(gamification_eligible_since=models.F("created_at"))

    for event in ClubGoodsImportEvent.objects.select_related(
        "origin__personal_goods"
    ).filter(effective_at__isnull=True):
        goods = getattr(event.origin, "personal_goods", None)
        if goods is not None and goods.status in ELIGIBLE_GOODS_STATUSES:
            ClubGoodsImportEvent.objects.filter(pk=event.pk).update(
                effective_at=event.created_at
            )

    for state in MetricSourceState.objects.filter(source_type="goods").iterator():
        goods = Goods.objects.filter(pk=state.source_id).first()
        if goods is None:
            continue
        scope = {
            "ip_id": goods.ip_id,
            "character_ids": sorted(
                goods.characters.values_list("id", flat=True)
            ),
            "category_id": goods.category_id,
            "is_official": bool(goods.is_official),
        }
        state.scope_hash = sha256(
            json.dumps(scope, sort_keys=True, default=str).encode("utf-8")
        ).hexdigest()
        state.save(update_fields=["scope_hash", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0049_clubgoodsimportevent_effective_at_and_more'),
        ('gamification', '0006_alter_achievementset_club_alter_reward_club'),
    ]

    operations = [
        migrations.RunPython(
            backfill_gamification_lifecycle,
            migrations.RunPython.noop,
        ),
    ]
