# Generated by Django 6.0.6 on 2026-09-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0051_guziimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='guziimage',
            name='client_upload_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='客户端上传幂等键'),
        ),
        migrations.AddConstraint(
            model_name='guziimage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_upload_id__isnull', False)), fields=('guzi', 'client_upload_id'), name='unique_guziimage_client_upload'),
        ),
    ]
