# Generated by Django 6.0.6 on 2026-06-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_backfill_owner_and_enforce_user_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagenode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
