# Generated by Django 6.0.6 on 2026-09-19 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='动作')),
                ('resource_type', models.CharField(db_index=True, max_length=100, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='资源 ID')),
                ('summary', models.CharField(max_length=500, verbose_name='摘要')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='脱敏变更')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to='users.user', verbose_name='操作管理员')),
            ],
            options={
                'verbose_name': '管理员操作日志',
                'verbose_name_plural': '管理员操作日志',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='admin_api_a_actor_i_daa140_idx'), models.Index(fields=['resource_type', 'created_at'], name='admin_api_a_resourc_e3e447_idx'), models.Index(fields=['action', 'created_at'], name='admin_api_a_action_57d10f_idx')],
            },
        ),
    ]
