# Generated by Django 6.0.6 on 2026-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict, verbose_name='审计载荷')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('next_attempt_at', models.DateTimeField(db_index=True, verbose_name='下次重试时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '管理员审计重试',
                'verbose_name_plural': '管理员审计重试',
                'ordering': ['resolved_at', 'next_attempt_at', 'id'],
                'indexes': [models.Index(fields=['resolved_at', 'next_attempt_at'], name='admin_api_a_resolve_e68b38_idx')],
            },
        ),
    ]
