# Generated by Django 6.0.6 on 2026-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_adminauditretry'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='幂等键'),
        ),
    ]
