# Generated by Django 6.0.6 on 2026-09-18 15:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='系列编码')),
                ('name', models.CharField(max_length=100, verbose_name='系列名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='系列说明')),
                ('badge_label', models.CharField(blank=True, default='', max_length=30, verbose_name='系列标签')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='结束时间')),
                ('is_limited', models.BooleanField(db_index=True, default=False, verbose_name='是否限时')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成就系列',
                'verbose_name_plural': '成就系列',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GamificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollout_at', models.DateTimeField(blank=True, null=True, verbose_name='累计起点')),
                ('initialized_at', models.DateTimeField(blank=True, null=True, verbose_name='基线初始化时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '游戏化配置',
                'verbose_name_plural': '游戏化配置',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='奖励编码')),
                ('name', models.CharField(max_length=100, verbose_name='奖励名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='奖励说明')),
                ('reward_type', models.CharField(choices=[('BADGE', '成就徽章'), ('PROFILE_FRAME', '头像框'), ('PROFILE_CARD_SKIN', '收藏卡皮肤'), ('JOURNAL_STICKER_PACK', '手帐贴纸包'), ('JOURNAL_BACKGROUND', '手帐背景'), ('SHOWCASE_THEME', '痛柜主题'), ('SHOWCASE_EFFECT', '痛柜效果')], db_index=True, max_length=40, verbose_name='奖励类型')),
                ('rarity', models.CharField(choices=[('common', '普通'), ('rare', '稀有'), ('epic', '史诗'), ('legendary', '限定')], default='common', max_length=20, verbose_name='稀有度')),
                ('asset', models.ImageField(blank=True, null=True, upload_to='gamification/rewards/', verbose_name='图片素材')),
                ('preset_key', models.CharField(blank=True, default='', help_text='主题、效果、皮肤和背景使用已注册的 preset_key。', max_length=80, verbose_name='前端预设编码')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '游戏化奖励',
                'verbose_name_plural': '游戏化奖励',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='成就编码')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='成就说明')),
                ('root_operator', models.CharField(choices=[('ALL', '全部满足'), ('ANY', '任一满足')], default='ALL', max_length=10, verbose_name='根规则')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('is_limited', models.BooleanField(db_index=True, default=False, verbose_name='是否限定')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='gamification.achievementset', verbose_name='所属系列')),
                ('rewards', models.ManyToManyField(blank=True, related_name='achievements', to='gamification.reward', verbose_name='奖励')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
                'ordering': ['set__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RewardAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='素材名称')),
                ('image', models.ImageField(upload_to='gamification/stickers/', verbose_name='素材图片')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gamification.reward', verbose_name='所属奖励')),
            ],
            options={
                'verbose_name': '奖励素材',
                'verbose_name_plural': '奖励素材',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ALL', '全部满足'), ('ANY', '任一满足')], default='ALL', max_length=10, verbose_name='组规则')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序值')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='gamification.achievement', verbose_name='所属成就')),
            ],
            options={
                'verbose_name': '规则组',
                'verbose_name_plural': '规则组',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('GOODS_QUANTITY', '新增谷子件数'), ('VALID_ALTARS', '有效角色痛柜数'), ('SPEND_AMOUNT', '累计消费金额'), ('DISTINCT_IP_COUNT', '去重 IP 数'), ('DISTINCT_CHARACTER_COUNT', '去重角色数')], db_index=True, max_length=40, verbose_name='统计指标')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='目标值')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='排序值')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='gamification.rulegroup', verbose_name='所属规则组')),
            ],
            options={
                'verbose_name': '规则条件',
                'verbose_name_plural': '规则条件',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', '未解锁'), ('unlocked', '可领取'), ('claimed', '已领取')], db_index=True, default='locked', max_length=20)),
                ('progress', models.JSONField(blank=True, default=dict, verbose_name='进度快照')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('unlocked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unseen', models.BooleanField(db_index=True, default=False, verbose_name='未读解锁')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='gamification.achievement', verbose_name='成就')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_achievements', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就',
                'ordering': ['achievement__set__order', 'achievement__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserEquippedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('PROFILE_FRAME', '头像框'), ('PROFILE_CARD_SKIN', '收藏卡皮肤'), ('DEFAULT_SHOWCASE_THEME', '默认痛柜主题'), ('DEFAULT_SHOWCASE_EFFECT', '默认痛柜效果')], db_index=True, max_length=40, verbose_name='装备槽位')),
                ('equipped_at', models.DateTimeField(auto_now=True, verbose_name='装备时间')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_by', to='gamification.reward', verbose_name='奖励')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_equipment', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户装备',
                'verbose_name_plural': '用户装备',
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='gamification.reward', verbose_name='奖励')),
                ('source_achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_grants', to='gamification.achievement', verbose_name='来源成就')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_rewards', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户奖励',
                'verbose_name_plural': '用户奖励',
                'ordering': ['reward__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOODS_QUANTITY', '谷子件数事件'), ('SPEND_AMOUNT', '消费金额事件'), ('VALID_ALTARS', '有效痛柜事件')], db_index=True, max_length=40, verbose_name='事件类型')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='事件数值')),
                ('source_type', models.CharField(db_index=True, max_length=40, verbose_name='来源类型')),
                ('source_id', models.CharField(db_index=True, max_length=100, verbose_name='来源 ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='事件快照')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时间')),
                ('idempotency_key', models.CharField(max_length=180, unique=True, verbose_name='幂等键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_events', to='users.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '指标事件',
                'verbose_name_plural': '指标事件',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['user', 'event_type', 'occurred_at'], name='gamificatio_user_id_3204ba_idx'), models.Index(fields=['user', 'occurred_at'], name='gamificatio_user_id_ca49cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricSourceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, max_length=40, verbose_name='来源类型')),
                ('source_id', models.CharField(db_index=True, max_length=100, verbose_name='来源 ID')),
                ('observed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('accrued_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observed_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('accrued_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_source_states', to='users.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '指标来源状态',
                'verbose_name_plural': '指标来源状态',
                'indexes': [models.Index(fields=['user', 'source_type'], name='gamificatio_user_id_b6b49d_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id'), name='unique_gamification_source_state')],
            },
        ),
        migrations.CreateModel(
            name='PublicBadgeSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='展示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_badge_selections', to='users.user', verbose_name='用户')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_selections', to='gamification.reward', verbose_name='徽章')),
            ],
            options={
                'verbose_name': '公开徽章选择',
                'verbose_name_plural': '公开徽章选择',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reward'), name='unique_public_badge_reward'), models.UniqueConstraint(fields=('user', 'order'), name='unique_public_badge_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('set', 'name'), name='unique_achievement_name_in_set'),
        ),
        migrations.AddConstraint(
            model_name='rewardasset',
            constraint=models.UniqueConstraint(fields=('reward', 'name'), name='unique_reward_asset_name'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement'),
        ),
        migrations.AddConstraint(
            model_name='userequippedreward',
            constraint=models.UniqueConstraint(fields=('user', 'slot'), name='unique_user_reward_slot'),
        ),
        migrations.AddConstraint(
            model_name='userreward',
            constraint=models.UniqueConstraint(fields=('user', 'reward'), name='unique_user_reward'),
        ),
    ]
