# Generated by Django 6.0.6 on 2026-09-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSyncFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, max_length=40, verbose_name='来源类型')),
                ('source_id', models.CharField(db_index=True, max_length=100, verbose_name='来源 ID')),
                ('error_message', models.TextField(verbose_name='错误信息')),
                ('attempts', models.PositiveIntegerField(default=1, verbose_name='失败次数')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, verbose_name='最近尝试时间')),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='恢复时间')),
            ],
            options={
                'verbose_name': '指标同步失败',
                'verbose_name_plural': '指标同步失败',
                'ordering': ['resolved_at', '-last_attempt_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id'), name='unique_gamification_sync_failure')],
            },
        ),
    ]
