# Generated by Django 6.0.6 on 2026-09-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_metricsyncfailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsourcestate',
            name='scope_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
