# Generated by Django 6.0.6 on 2026-09-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_metricsourcestate_scope_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricevent',
            name='event_type',
            field=models.CharField(choices=[('GOODS_QUANTITY', '谷子件数事件'), ('SPEND_AMOUNT', '消费金额事件'), ('VALID_ALTARS', '有效痛柜事件'), ('SCOPE_REFRESH', '维度刷新事件')], db_index=True, max_length=40, verbose_name='事件类型'),
        ),
    ]
