# Generated by Django 6.0.6 on 2026-09-19 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_metricevent_event_type'),
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='first_published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='社团成就首次实际可见的时间；统计起点不早于该时间。', null=True, verbose_name='首次发布时间'),
        ),
        migrations.AddField(
            model_name='achievementset',
            name='club',
            field=models.ForeignKey(blank=True, help_text='为空表示平台成就系列。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamification_sets', to='users.club', verbose_name='所属社团'),
        ),
        migrations.AddField(
            model_name='reward',
            name='club',
            field=models.ForeignKey(blank=True, help_text='为空表示平台奖励。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamification_rewards', to='users.club', verbose_name='所属社团'),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='metric',
            field=models.CharField(choices=[('GOODS_QUANTITY', '新增谷子件数'), ('VALID_ALTARS', '有效角色痛柜数'), ('SPEND_AMOUNT', '累计消费金额'), ('DISTINCT_IP_COUNT', '去重 IP 数'), ('DISTINCT_CHARACTER_COUNT', '去重角色数'), ('CLUB_GOODS_QUANTITY', '社团商品导入件数'), ('CLUB_SPEND_AMOUNT', '社团商品累计公开价')], db_index=True, max_length=40, verbose_name='统计指标'),
        ),
        migrations.AddIndex(
            model_name='achievementset',
            index=models.Index(fields=['club', 'is_active'], name='gamificatio_club_id_7818c1_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['club', 'is_active'], name='gamificatio_club_id_8a1ebe_idx'),
        ),
    ]
