# Generated by Django 6.0.6 on 2026-09-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_achievement_first_published_at_achievementset_club_and_more'),
        ('users', '0007_club_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementset',
            name='club',
            field=models.ForeignKey(blank=True, help_text='为空表示平台成就系列。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gamification_sets', to='users.club', verbose_name='所属社团'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='club',
            field=models.ForeignKey(blank=True, help_text='为空表示平台奖励。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gamification_rewards', to='users.club', verbose_name='所属社团'),
        ),
    ]
